import "package:flutter/material.dart";

ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: lightScheme(),
  fontFamily: 'outfit',
);
ThemeData darkTheme = ThemeData(
  useMaterial3: true,
  colorScheme: darkScheme(),
  fontFamily: 'outfit',
);
ColorScheme lightScheme() {
  return const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff8d495a),
    surfaceTint: Color(0xff8d495a),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffffd9df),
    onPrimaryContainer: Color(0xff713342),
    secondary: Color(0xff75565c),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffffd9df),
    onSecondaryContainer: Color(0xff5b3f45),
    tertiary: Color(0xff7a5732),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffffdcbc),
    onTertiaryContainer: Color(0xff60401d),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff93000a),
    surface: Color(0xfffff8f7),
    onSurface: Color(0xff22191b),
    onSurfaceVariant: Color(0xff524345),
    outline: Color(0xff847375),
    outlineVariant: Color(0xffd6c2c4),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff382e2f),
    inversePrimary: Color(0xffffb1c1),
    primaryFixed: Color(0xffffd9df),
    onPrimaryFixed: Color(0xff3a0718),
    primaryFixedDim: Color(0xffffb1c1),
    onPrimaryFixedVariant: Color(0xff713342),
    secondaryFixed: Color(0xffffd9df),
    onSecondaryFixed: Color(0xff2b151a),
    secondaryFixedDim: Color(0xffe4bdc3),
    onSecondaryFixedVariant: Color(0xff5b3f45),
    tertiaryFixed: Color(0xffffdcbc),
    onTertiaryFixed: Color(0xff2c1600),
    tertiaryFixedDim: Color(0xffecbe91),
    onTertiaryFixedVariant: Color(0xff60401d),
    surfaceDim: Color(0xffe7d6d8),
    surfaceBright: Color(0xfffff8f7),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfffff0f1),
    surfaceContainer: Color(0xfffbeaeb),
    surfaceContainerHigh: Color(0xfff5e4e6),
    surfaceContainerHighest: Color(0xffefdee0),
  );
}

ColorScheme darkScheme() {
  return const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffffb1c1),
    surfaceTint: Color(0xffffb1c1),
    onPrimary: Color(0xff551d2c),
    primaryContainer: Color(0xff713342),
    onPrimaryContainer: Color(0xffffd9df),
    secondary: Color(0xffe4bdc3),
    onSecondary: Color(0xff43292e),
    secondaryContainer: Color(0xff5b3f45),
    onSecondaryContainer: Color(0xffffd9df),
    tertiary: Color(0xffecbe91),
    onTertiary: Color(0xff462a09),
    tertiaryContainer: Color(0xff60401d),
    onTertiaryContainer: Color(0xffffdcbc),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xff93000a),
    onErrorContainer: Color(0xffffdad6),
    surface: Color(0xff191113),
    onSurface: Color(0xffefdee0),
    onSurfaceVariant: Color(0xffd6c2c4),
    outline: Color(0xff9f8c8f),
    outlineVariant: Color(0xff524345),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffefdee0),
    inversePrimary: Color(0xff8d495a),
    primaryFixed: Color(0xffffd9df),
    onPrimaryFixed: Color(0xff3a0718),
    primaryFixedDim: Color(0xffffb1c1),
    onPrimaryFixedVariant: Color(0xff713342),
    secondaryFixed: Color(0xffffd9df),
    onSecondaryFixed: Color(0xff2b151a),
    secondaryFixedDim: Color(0xffe4bdc3),
    onSecondaryFixedVariant: Color(0xff5b3f45),
    tertiaryFixed: Color(0xffffdcbc),
    onTertiaryFixed: Color(0xff2c1600),
    tertiaryFixedDim: Color(0xffecbe91),
    onTertiaryFixedVariant: Color(0xff60401d),
    surfaceDim: Color(0xff191113),
    surfaceBright: Color(0xff413738),
    surfaceContainerLowest: Color(0xff140c0e),
    surfaceContainerLow: Color(0xff22191b),
    surfaceContainer: Color(0xff261d1f),
    surfaceContainerHigh: Color(0xff312829),
    surfaceContainerHighest: Color(0xff3c3234),
  );
}
